---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev:v1.6.7

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      # Build the shared module before it is imported:
      - run: yarn run build
      - run: cd ui && yarn run build
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ui/node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: cd ui && yarn run lint
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ui/node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      # Build the shared module before it is imported:
      - run: yarn run build
      - run: cd ui && yarn run test --max-workers=2
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ui/node_modules

  build-legacy:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      # Build the shared module before it is imported:
      - run: yarn run build
      - run: cd legacy && yarn run build
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - legacy/node_modules

  lint-legacy:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: cd legacy && yarn run lint
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - legacy/node_modules

  test-legacy:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      # Build the shared module before it is imported:
      - run: yarn run build
      - run: cd legacy && yarn run test --max-workers=2
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - legacy/node_modules

  build-shared:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: cd shared && yarn run build
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - shared/node_modules

  lint-shared:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: cd shared && yarn run lint
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - shared/node_modules

  test-shared:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: cd shared && yarn run test --max-workers=2
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - shared/node_modules

  lint-proxy:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: cd proxy && yarn run lint
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - proxy/node_modules

  test-cypress:
    docker:
      - image: cypress/base:12.13.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!
      - run: yarn test-cypress

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - build
      - lint
      - test
      - build-legacy
      - lint-legacy
      - test-legacy
      - build-shared
      - lint-shared
      - test-shared
      - lint-proxy
      - test-cypress
